// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppBroadcast
NumericMatrix cppBroadcast(NumericVector offsets, LogicalMatrix resets);
RcppExport SEXP _osutools_cppBroadcast(SEXP offsetsSEXP, SEXP resetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type resets(resetsSEXP);
    rcpp_result_gen = Rcpp::wrap(cppBroadcast(offsets, resets));
    return rcpp_result_gen;
END_RCPP
}
// cppSimulateKey
DataFrame cppSimulateKey(NumericVector offsets, CharacterVector types, double decay_ms, double stress);
RcppExport SEXP _osutools_cppSimulateKey(SEXP offsetsSEXP, SEXP typesSEXP, SEXP decay_msSEXP, SEXP stressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< double >::type decay_ms(decay_msSEXP);
    Rcpp::traits::input_parameter< double >::type stress(stressSEXP);
    rcpp_result_gen = Rcpp::wrap(cppSimulateKey(offsets, types, decay_ms, stress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_osutools_cppBroadcast", (DL_FUNC) &_osutools_cppBroadcast, 2},
    {"_osutools_cppSimulateKey", (DL_FUNC) &_osutools_cppSimulateKey, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_osutools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
