// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_broadcast
NumericMatrix cpp_broadcast(NumericVector offsets, LogicalMatrix resets);
RcppExport SEXP _osutools_cpp_broadcast(SEXP offsetsSEXP, SEXP resetsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< LogicalMatrix >::type resets(resetsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_broadcast(offsets, resets));
    return rcpp_result_gen;
END_RCPP
}
// cpp_simulate_key
DataFrame cpp_simulate_key(NumericVector offsets, CharacterVector types, double decay_alpha, double decay_beta, double stress);
RcppExport SEXP _osutools_cpp_simulate_key(SEXP offsetsSEXP, SEXP typesSEXP, SEXP decay_alphaSEXP, SEXP decay_betaSEXP, SEXP stressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type types(typesSEXP);
    Rcpp::traits::input_parameter< double >::type decay_alpha(decay_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type decay_beta(decay_betaSEXP);
    Rcpp::traits::input_parameter< double >::type stress(stressSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_simulate_key(offsets, types, decay_alpha, decay_beta, stress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_osutools_cpp_broadcast", (DL_FUNC) &_osutools_cpp_broadcast, 2},
    {"_osutools_cpp_simulate_key", (DL_FUNC) &_osutools_cpp_simulate_key, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_osutools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
