#' Calculates alpha via a simple function
#'
#' @description
#' Doesn't really need to exist as a separate function
#' but it acts as a wrapper
#'
#' @param chart The **data.frame** generated by
#' diff.broadcast
#' @param mapping The **data.frame** generated by
#' create.move.mapping
#' @param f.alpha The **function** to calculate alpha
#' with (diffs, moves.values) respectively
#'
#' @export

alphaCalc <- function(chart, mapping, f.alpha){

  chart <- merge(chart, mapping, by = c('keys.froms', 'keys.tos'))
  chart$alphas <- f.alpha(diffs = chart$diffs,
                          moves.values = chart$moves.values)
  chart$alphas[chart$alphas < 0] <- 0

  return(chart)
}
