#' Extracts chart details to use with Models
#'
#' @description This acts as a wrapper for more
#' detailed functions. Outputs chart.ext.
#'
#' @param chart Chart generated by chartParse
#' @param keyset.select Read ?createMoveMapping
#' for more details
#' @param keyset Read ?createMoveMapping
#' for more details
#' @export
chartExtract <- function(chart,
                         keyset.select = NA,
                         keyset = NA) {
  chart.bcst <- diffBroadcast(chart)
  chart.ext <- merge(chart.bcst,
                     chartFngMapping(
                       keyset.select = keyset.select,
                       keyset = keyset,
                       include.details = T
                     ),
                     by = c('keys.froms', 'keys.tos'))
  return(chart.ext)
}

# d <- chartExtract(
#   chartParse("../osutools_ui/local_tests/osu/4/Betwixt & Between - out of Blue (Shoegazer) [Abyss].osu"),
#   keyset.select = '4', keyset = NA)
#
# model.jackInv(d)
