#' Extracts chart details to use with Models
#'
#' @description This acts as a wrapper for more
#' detailed functions. Outputs chart.ext.
#'
#' @param chart Chart generated by chartParse
#' @param keyset.select Read ?createMoveMapping
#' for more details
#' @param keyset Read ?createMoveMapping
#' for more details
#' @param ignore.types Types of notes to ignore
#'
#' ?diffBroadcast for more details
#' @return Returns a data.frame compatible with
#' models
#' @export
chartExtract <- function(chart,
                         keyset.select = NA,
                         keyset = NA,
                         ignore.types = c('lnotel')) {
  chart.bcst <- diffBroadcast(chart, ignore.types = ignore.types)
  chart.ext <- merge(chart.bcst,
                     chartFngMapping(
                       keyset.select = keyset.select,
                       keyset = keyset,
                       include.details = T
                     ),
                     by = c('keys.froms', 'keys.tos'))
  return(chart.ext)
}
