#' Exports all models into a tabular format
#'
#' @param m.mtn model generated by model.motion
#' @param m.dns model generated by model.density
#' @param m.mnp model generated by model.manipulation
#' @param m.lng model generated by model.longNote
#'
#' @importFrom magrittr %>%
#' @importFrom dplyr rename
#' @importFrom purrr reduce
#' @importFrom tidyr replace_na
#'
#' @export

model.export <- function(m.mtn, m.dns, m.mnp, m.lng){
  # This joins all models
  model <- list(m.mtn, m.dns, m.mnp, m.lng) %>%
    purrr::reduce(dplyr::left_join, by = 'offsets') %>%
    dplyr::rename(mtn.vals = 2,
                  dns.vals = 3,
                  mnp.vals = 4,
                  lng.vals = 5) %>%
    tidyr::replace_na(0)
}
