#' Simulates the Models through types
#'
#' @param m.jck model generated by model.jackInv
#' @param m.mtn model generated by model.motion
#' @param m.dns model generated by model.density
#' @param jck.pow power factor for jck
#' @param mtn.pow power factor for mtn
#' @param dns.pow power factor for dns
#' @param decay.ms stress decay per ms
#' @param stress.init stress to start off with
#' @param bin.size the bins size for model smoothing
#' The smaller the bin size the more suspectible the
#' model will be to sudden spikes.
#'
#' @importFrom magrittr %<>% %>%
#' @importFrom dplyr mutate
#' @importFrom rlang .data
#' @importFrom purrr reduce
#' @export

model.sim <- function(m.jck, m.mtn, m.dns,
                      jck.pow, mtn.pow, dns.pow,
                      decay.ms = 0.5,
                      stress.init = 0,
                      bin.size = 5000){

  # This joins all models
  model <- list(m.jck, m.mtn, m.dns) %>%
    purrr::reduce(dplyr::left_join, by = 'offsets') %>%
    dplyr::rename(jck.vals = 2,
                  mtn.vals = 3,
                  dns.vals = 4) %>%
    dplyr::mutate(bins = (.data$offsets %/% bin.size) * bin.size,
                  values =
                    ((.data$mtn.vals * 10) + 1) ** mtn.pow +
                    (.data$dns.vals + 1) ** dns.pow +
                    ((.data$jck.vals * 1000) + 1) ** jck.pow)

  # Simulation is done before binning
  sim <- .cppSimulateKey(model$offsets,
                         model$values,
                         decay_ms = decay.ms,
                         stress_init = stress.init)

  # Binning
  model %<>%
    dplyr::group_by(.data$bins) %>%
    dplyr::summarise(values = mean(.data$values))


  return(list("sim" = sim, "model" = model))
}
