#' Simulates the Models through types
#'
#' @param m.jck model generated by model.jackInv
#' @param m.mtn model generated by model.motion
#' @param m.dns model generated by model.density
#' @param decay.ms stress decay per ms
#' @param stress.init stress to start off with
#'
#' @importFrom magrittr %<>% %>%
#' @importFrom dplyr mutate
#' @importFrom rlang .data
#' @importFrom purrr reduce
#' @export

model.sim <- function(m.jck, m.mtn, m.dns,
                      decay.ms = 0.5,
                      stress.init = 0){

  # This joins all models
  model <- list(m.jck, m.mtn, m.dns) %>%
    purrr::reduce(dplyr::left_join, by = 'offsets') %>%
    dplyr::rename(jck.vals = 2,
                  mtn.vals = 3,
                  dns.vals = 4) %>%
    dplyr::mutate(values = .data$mtn.vals * .data$dns.vals)

  sim <- .cppSimulateKey(model$offsets,
                         model$values,
                         decay_ms = decay.ms,
                         stress_init = stress.init)
  return(sim)
}
