#' Transfers stress to other keys
#'
#' @description Depending on the function provided,
#' stress transfer may vary. However, in most cases
#' these stress transfers are assumptions on playstyle
#'
#' This will not overwrite the current stress columns,
#' it will generate a separate one.
#'
#' @param chart The **data.frame** generated by f.chart.sim
#' @param tf.group A **list** of key groups to have internal
#' stress transfer. There's a specific format to use.
#' @param func A **function** to use on the group. Refer to
#' examples for specifications.
#'
#' @examples
#' The function also has a specific format
#' `function(stress.main, stress.others){ return(stress.main) }`
#' `stress.main` is the current key's stress value
#' `stress.others` is the other key's stress values in a vector.
#'
#' The function must return the stress value.
#'
#' @export
stressTransfer <- function(chart,
                           transfer.group,
                           func){
  chart <- chart.sim %>%
    dcast(offsets ~ keys, value.var = 'types')
}
