#' Simulates the Stress through types
#'
#' @description
#'
#' @param chart Chart generated by `f.stress.mapper`
#' @param stress.init The **numeric** of 'stress' to
#' initialize the simulation with
#'
#' @export

stressSim <- function(chart,
                      stress.init = 0.0,
                      decay_ms = 0.01){

  # Allocate columns in advance
  chart %<>%
    arrange(offsets)

  # Chart frame is required to pad out decay calculations
  # where there aren't spikes.
  chart.frame <- data.frame(offsets=unique(chart$offsets))

  # We will be looping through the chart by key
  chart.k.split <- split(x = chart, f = chart$keys)

  for (key in 1:length(chart.k.split)){
    chart.k <- chart.k.split[[key]]
    chart.k %<>%
      merge(chart.frame, by='offsets', all=T) %>%
      mutate(is.spike = !is.na(types))

    chart.k.sim <- .cppSimulateKey(
      chart.k$offsets,
      chart.k$types,
      decay_ms = decay_ms,
      stress = 0
    )

    chart.k.sim %<>%
      mutate(keys = key)

    chart.k.split[[key]] <- chart.k.sim
  }

  # Join charts of different keys into one
  chart <- bind_rows(chart.k.split)
  return(chart)
}
